### ISSUE TITLE
Strange black space

### ISSUE THREAD

**Issue by mariusglauer** [JoeFryer/JDFPeekaboo#1] opened 2015-02-21 08:37 UTC
Hi,
if you have an UIRefreshControl for your tableView which acts as the scrollView, the most top column is always getting black while scrolling.

**Comment by JoeFryer** [comment] 2015-02-21 12:54
Hi @gbhrdt,

Are you able to setup a sample project to show this? I've just tried this myself and I couldn't reproduce it.

Joe

**Comment by mariusglauer** [comment] 2015-02-21 22:40
At first I thought the UIRefreshControl might be the problem, it turned out it was something different.
After some time of examining and experimenting with your code, it turned out that my scrollView had some weird insets at the top which are caused by the interface builder. This resulted in a black cell at the top. I wasn't able to reproduce it with your Demo project as well, but it might have been my UITabBarController (If I set the bottomBar to the UITabBarController's tabBar, there was also black space when it was hidden.

My setup:

```
UITabBarController -> UINavigationController -> UITableViewController with JDFPeekaboo
                   -> UINavigationController -> ...
```

I had to select the UITableViewController's "Extend edges > Under Opaque Bars" setting to fix this - but I don't really know why. Maybe there is a better way to fix this or you should add that in your README.

If you still can't reproduce it with my setup, let me know and I'll upload my current project.

Cheers

**Comment by JoeFryer** [comment] 2015-02-23 10:23
Ah, I think I see what you mean. It sounds like your table view isn't extending underneath the navigation bar/tab bar, so, when `JDFPeekaboo` moves them out of the way, there is nothing underneath them to reveal. You're right, I should probably add this to the README. Thanks, @gbhrdt.

**Comment by JoeFryer** [comment] 2015-02-23 12:17
Updated README - thanks @gbhrdt. I'm going to close this.

**Closed as completed by JoeFryer** 2015-02-23 12:17 UTC
